######################################################################
# Automatically generated by qmake (2.01a) ?? 26. ??? 14:09:10 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lfftw3 -Lc://work//Desktop//Qt//4.8.1//mingw//include//

# Input
SOURCES += main.cpp
