######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 30 11:00:45 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += f.h
SOURCES += f.cpp main.cpp
