div: plus minus mult

plus: lect04_task05.cpp
	g++ lect04_task05.cpp -s -o plus -DPLUS

minus: lect04_task05.cpp
	g++ lect04_task05.cpp -s -o minus -DMINUS

mult: lect04_task05.cpp
	g++ lect04_task05.cpp -s -o mult -DMULT

div: lect04_task05.cpp
	g++ lect04_task05.cpp -s -o div -DDIV
