######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 15 11:35:17 2013
######################################################################

TEMPLATE = app
CONFIG -= qt
CONFIG += console
QMAKE_CXXFLAGS += -std=c++0x

# Input
SOURCES += main.cpp
