######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 9 13:13:29 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ..
INCLUDEPATH += . ..
CONFIG += qtestlib
LIBS += -lfftw3

# Input
SOURCES += test.cpp matrix.cpp
