######################################################################
# Automatically generated by qmake (2.01a) ?? 26. ??? 18:45:48 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += vec3.h
SOURCES += main.cpp vec3.cpp
