######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 1 12:14:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ..
INCLUDEPATH += . ..
CONFIG += qtestlib

# Input
SOURCES += test_tensor.cpp Tensor4.cpp matrix.cpp
