######################################################################
# Automatically generated by qmake (2.01a) ?? 16. ??? 17:37:07 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . test_matrix
INCLUDEPATH += .

# Input
HEADERS += Matrix.h
SOURCES += main.cpp Matrix.cpp
LIBS += -L"C://work//fftw//lib" -lfftw3