######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 26 12:22:28 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
