######################################################################
# Automatically generated by qmake (2.01a) ?? 4. ??? 10:14:17 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += c://cpp_prak//Qt_SDK//Desktop//Qt//4.7.4//mingw//include//
LIBS += libfftw3-3 -Lc://cpp_prak//Qt_SDK//mingw//include//


# Input
HEADERS += fftwmatrix.h fftwplan.h
SOURCES += fftwmatrix.cpp main.cpp fftwplan.cpp
