######################################################################
# Automatically generated by qmake (2.01a) ?? 9. ??? 15:00:15 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ..
INCLUDEPATH += . ..
CONFIG += qtestlib
LIBS += -L"C://work//fftw//lib" -lfftw3

# Input
SOURCES += test.cpp Matrix.cpp
