######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 1 13:08:05 2013
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += . ..
INCLUDEPATH += . ..

# Input
SOURCES += testmatrix.cpp matrix.cpp
