######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 1 12:14:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ..
INCLUDEPATH += . ..
CONFIG += qtestlib
QMAKE_CXXFLAGS += -O2

# Input
SOURCES += testutil.cpp\
 util.cpp\
 vec3.cpp\
 matrix.cpp\
polynom.cpp
