######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 1 12:14:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ..
INCLUDEPATH += . ..
CONFIG += qtestlib

# Input
SOURCES += testvec3.cpp vec3.cpp
