######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 26 14:58:20 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += field.h robot.h
SOURCES += field.cpp main.cpp robot.cpp
