# mingw32-make prog_ura => выполнится только одно правило

#all_targets: plus minus product division

plus: main.cpp
	g++ main.cpp -o plus -Dplus
	
minus: main.cpp
	g++ main.cpp -o minus -Dminus
	
product: main.cpp
	g++ main.cpp -o product -Dproduct
	
division: main.cpp
	g++ main.cpp -o division -Ddivision