######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 17 12:27:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . 

CONFIG += qwt

FORMS = demodialog.ui

# Input
SOURCES += main.cpp ourdialog.cpp
HEADERS += ourdialog.h
