######################################################################
# Automatically generated by qmake (2.01a) ?? 26. ??? 13:03:08 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
