######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 7 12:43:45 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++0x

# Input
SOURCES += main.cpp
