######################################################################
# Automatically generated by qmake (2.01a) ?? 7. ??? 12:48:13 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=gnu++0x

# Input
SOURCES += main.cpp
