######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 7 14:39:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
